import os
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [os.path.join(cwd, '..', 'include')]

group = DefineGroup('OSAL_RTThread', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
