import os
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [
    cwd,
    os.path.join(cwd, '..'),
    os.path.join(cwd, '..', '..', 'osal', 'include'),
]

group = DefineGroup('RtClaw_Core', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
