# Meson cross-file for QEMU vexpress-a9 (RT-Thread)
# Usage: meson setup <builddir> <srcdir> --cross-file <this-file>

[binaries]
c = 'arm-none-eabi-gcc'
ar = 'arm-none-eabi-ar'
strip = 'arm-none-eabi-strip'

[host_machine]
system = 'none'
cpu_family = 'arm'
cpu = 'cortex-a7'
endian = 'little'

[built-in options]
c_args = ['-march=armv7-a', '-mtune=cortex-a7', '-msoft-float', '-ftree-vectorize', '-ffast-math', '-funwind-tables', '-fno-strict-aliasing', '-Wno-cpp']

[project options]
osal = 'rtthread'
