import os
from building import *

cwd = GetCurrentDir()
objs = []

# claw_init.c in src/ root
src = Glob('*.c')
CPPPATH = [
    cwd,
    os.path.join(cwd, 'core'),
    os.path.join(cwd, 'services', 'swarm'),
    os.path.join(cwd, 'services', 'net'),
    os.path.join(cwd, 'services', 'ai'),
    os.path.join(cwd, '..', 'osal', 'include'),
]
group = DefineGroup('RtClaw_Init', src, depend = [''], CPPPATH = CPPPATH)
objs = objs + group

# Subdirectories
for d in os.listdir(cwd):
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
